apiVersion: v1
kind: Secret
metadata:
  name: thermal-dtls-secret
  namespace: default
type: Opaque
stringData:
  DTLS_PSK_IDENTITY: "thermal-sensor-01"
  DTLS_PSK_KEY_HEX: "32b450ab58147f9da18d96bd7dee4304b49c6a07d03e20d8774734e36d2346bc"
  DTLS_COOKIE_SECRET_HEX: "7a1d42e9c0b3118fe4d26a55bc9d73f14a267c5e90df11b8c1a45e62fbd30c7a"
