# Dockerfile.base
FROM ubuntu:22.04

# 시간 걸리는 설치 작업 몰아넣기
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libboost-all-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*
