# Dockerfile.base
FROM ubuntu:22.04

# 시간 걸리는 설치 작업 몰아넣기 (Asio 충돌 방지 포함)
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libboost-all-dev \
    libssl-dev \
    libmosquitto-dev \    
    libmosquittopp-dev \
    libmysqlclient-dev \
    libcurl4-openssl-dev \
    pkg-config \
    nlohmann-json3-dev \
    && apt-get purge -y libasio-dev || true \
    && rm -rf /var/lib/apt/lists/*
