[platformio]
default_envs = firebeetle2-esp32-c5

[env:firebeetle2-esp32-c5]
platform = espressif32@6.12.0
board = esp32-c5-devkitc-1
framework = espidf
monitor_speed = 115200
debug_tool = esp-builtin
debug_init_break = tbreak app_main
upload_speed = 460800

board_upload.flash_size = 4MB
board_build.flash_mode = dio
board_build.f_cpu = 240000000L

board_build.embed_txtfiles = 
    src/certs/rootCA.crt
    src/certs/client-stm32.crt
    src/certs/client-stm32.key

build_flags =
    -DWIFI_SSID=\"6th_team3\"
    -DWIFI_PASS=\"6th_team3\"
