# Use pre-built environment image
FROM hjuohj/qt-client-base:latest

# Set working directory
WORKDIR /app

# Copy source code into the container
COPY . /app

# (Optional) Pre-configure environment variables if needed
ENV QT_SELECT=qt6
