/*
 * Copyright (c) 2015, Freescale Semiconductor, Inc.
 * Copyright 2016 - 2018 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _USB_DEVICE_CONFIG_H_
#define _USB_DEVICE_CONFIG_H_

#define USB_DEVICE_CONFIG_KHCI (0U)
#define USB_DEVICE_CONFIG_EHCI (1U)
#define USB_DEVICE_CONFIG_LPCIP3511FS (0U)
#define USB_DEVICE_CONFIG_LPCIP3511HS (0U)

#define USB_DEVICE_CONFIG_NUM \
    (USB_DEVICE_CONFIG_KHCI + USB_DEVICE_CONFIG_EHCI + USB_DEVICE_CONFIG_LPCIP3511FS + USB_DEVICE_CONFIG_LPCIP3511HS)

#ifndef USB_DEVICE_CONFIG_HID
#define USB_DEVICE_CONFIG_HID (0U)
#endif

#ifndef USB_DEVICE_CONFIG_CDC_ACM
#define USB_DEVICE_CONFIG_CDC_ACM (1U)
#endif

#ifndef USB_DEVICE_CONFIG_CDC_RNDIS
#define USB_DEVICE_CONFIG_CDC_RNDIS (0U)
#endif

#ifndef USB_DEVICE_CONFIG_MSC
#define USB_DEVICE_CONFIG_MSC (0U)
#endif

#ifndef USB_DEVICE_CONFIG_AUDIO
#define USB_DEVICE_CONFIG_AUDIO (0U)
#endif

#ifndef USB_DEVICE_CONFIG_PHDC
#define USB_DEVICE_CONFIG_PHDC (0U)
#endif

#ifndef USB_DEVICE_CONFIG_VIDEO
#define USB_DEVICE_CONFIG_VIDEO (0U)
#endif

#ifndef USB_DEVICE_CONFIG_CCID
#define USB_DEVICE_CONFIG_CCID (0U)
#endif

#ifndef USB_DEVICE_CONFIG_PRINTER
#define USB_DEVICE_CONFIG_PRINTER (0U)
#endif

#ifndef USB_DEVICE_CONFIG_DFU
#define USB_DEVICE_CONFIG_DFU (0U)
#endif

#define USB_DEVICE_CONFIG_SELF_POWER (1U)
#define USB_DEVICE_CONFIG_ENDPOINTS (4U)
#define USB_DEVICE_CONFIG_USE_TASK (0U)
#define USB_DEVICE_CONFIG_MAX_MESSAGES (8U)
#define USB_DEVICE_CONFIG_USB20_TEST_MODE (0U)
#define USB_DEVICE_CONFIG_CV_TEST (0U)
#define USB_DEVICE_CONFIG_COMPLIANCE_TEST (0U)

#if ((defined(USB_DEVICE_CONFIG_EHCI)) && (USB_DEVICE_CONFIG_EHCI > 0U))
#define USB_DEVICE_CONFIG_EHCI_MAX_DTD (16U)
#define USB_DEVICE_CONFIG_EHCI_ID_PIN_DETECT (0U)
#endif

#define USB_DEVICE_CONFIG_KEEP_ALIVE_MODE (0U)

#ifndef USB_DEVICE_CONFIG_BUFFER_PROPERTY_CACHEABLE
#define USB_DEVICE_CONFIG_BUFFER_PROPERTY_CACHEABLE (0U)
#endif

#define USB_DEVICE_CONFIG_LOW_POWER_MODE (0U)
#define USB_DEVICE_CONFIG_REMOTE_WAKEUP (0U)

#ifndef USB_DEVICE_CONFIG_DETACH_ENABLE
#define USB_DEVICE_CONFIG_DETACH_ENABLE (0U)
#endif

#define USB_DEVICE_CONFIG_ERROR_HANDLING (0U)
#define USB_DEVICE_CHARGER_DETECT_ENABLE (0U)

#endif /* _USB_DEVICE_CONFIG_H_ */
