# -----------------------------------------------------------
# Crow 웹 서버 배포 (Deployment)
# -----------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crow-server
  template:
    metadata:
      labels:
        app: crow-server
    spec:
      # 파일이 있는 노드(pi-worker1)에 고정
      nodeSelector:
        kubernetes.io/hostname: pi-worker1
      
      containers:
      - name: crow-server
        image: docker.io/hjuohj/crow-server:latest
        imagePullPolicy: Always 
        
        ports:
        - containerPort: 8080
        
        # DB 접속 정보
        env:
        - name: DB_HOST
          value: "mariadb-service"
        - name: DB_USER
          value: "veda_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: user-password

        # 마운트
        volumeMounts:
        - name: recordings
          mountPath: /app/recordings

      volumes:
      - name: recordings
        # PVC 대신 호스트 경로 직접 사용 (MediaMTX와 공유)
        hostPath:
          path: /home/pi/cctv-recordings
          type: DirectoryOrCreate

---
# -----------------------------------------------------------
# 외부 접속용 서비스 (Service)
# -----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: crow-server-service
spec:
  # 내부 전용 IP 할당 (Nginx Gateway를 통해서만 접근 가능)
  type: ClusterIP
  selector:
    app: crow-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080