apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  # 여기에 실제 사용할 비밀번호를 적습니다.
  # (base64 인코딩 없이 그냥 문자열로 적어도, 쿠버네티스가 알아서 인코딩해줍니다)
  root-password: "6th_team3"
  user-password: "team3"