apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  # ���⿡ ���� ����� ��й�ȣ�� �����ϴ�.
  # (base64 ���ڵ� ���� �׳� ���ڿ��� ���, ������Ƽ���� �˾Ƽ� ���ڵ����ݴϴ�)
  root-password: "PASSWORD_HERE"
  user-password: "PASSWORD_HERE"