user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    upstream crow_backend {
        server crow-server-service:8080;
    }

    upstream mediamtx_hls {
        server mediamtx-service:8888;
    }

    server {
        listen 443 ssl;
        server_name _;

        # 인증서는 Docker 이미지 빌드 시 /etc/nginx/certs/ 경로에 포함됨
        ssl_certificate     /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;
        ssl_client_certificate /etc/nginx/certs/rootCA.crt;
        ssl_verify_client optional;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_set_header X-Device-Verify $ssl_client_verify;
            proxy_set_header X-Device-ID $ssl_client_s_dn;
            proxy_pass http://crow_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /hls/ {
            proxy_pass http://mediamtx_hls/;
            proxy_set_header Host $host;
        }
    }

    server {
        listen 80;
        server_name _;
        location / {
            return 301 https://$host$request_uri;
        }
    }
}

stream {
    upstream mediamtx_rtsp {
        server mediamtx-service:8554;
    }
    
    upstream mosquitto_backend {
        server mqtt-service:1883;
    }

    server {
        listen 8883 ssl;
        ssl_certificate         /etc/nginx/certs/server.crt;
        ssl_certificate_key     /etc/nginx/certs/server.key;
        ssl_client_certificate  /etc/nginx/certs/rootCA.crt;
        ssl_verify_client       on;
        proxy_pass mosquitto_backend;
    }

    server {
        listen 8554;
        proxy_pass mediamtx_rtsp;
    }
}
